name       : gupnp-dlna
version    : 0.12.0
release    : 11
source     :
    - https://download.gnome.org/sources/gupnp-dlna/0.12/gupnp-dlna-0.12.0.tar.xz : 3d53b96f85bc5628d33e367ec9bf2adb38ef2b34d7ad0434a6ba0cf4ad9048e6
license    : LGPL-2.0-only
component  : network.util
summary    : GUPnP DLNA utility for DLNA-related tasks.
description: |
    GUPnP DLNA is a small utility library that aims to ease the DLNA-related tasks such as media profile guessing, transcoding to a given profile, etc.
builddeps  :
    - pkgconfig(gstreamer-pbutils-1.0)
    - pkgconfig(glib-2.0)
    - pkgconfig(libxml-2.0)
    - gtk-doc
    - vala
setup      : |
    # this package forces -O0 over our -O2 which breaks FORTIFY_SOURCE
    %meson_configure
build      : |
    %ninja_build
install    : |
    # this is just a really bad package now.
    %ninja_install
