name       : gupnp-dlna
version    : 0.10.3
release    : 1
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gupnp-dlna/0.10/gupnp-dlna-0.10.3.tar.xz : dcbe5f5f721c76781f3d3bb1bfcdf9818df0905203d4e5759aecb9cb127872d5
license    : LGPL-2.0
summary    : GUPnP DLNA utility for DLNA-related tasks.
description: |
    GUPnP DLNA is a small utility library that aims to ease the DLNA-related tasks such as media profile guessing, transcoding to a given profile, etc.
builddeps  :
    - pkgconfig(libxml-2.0)
    - pkgconfig(glib-2.0)
    - pkgconfig(gobject-2.0)
    - pkgconfig(gmodule-2.0)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
