name       : gupnp-dlna
version    : 0.10.3
release    : 2
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gupnp-dlna/0.10/gupnp-dlna-0.10.3.tar.xz : dcbe5f5f721c76781f3d3bb1bfcdf9818df0905203d4e5759aecb9cb127872d5
license    : LGPL-2.0
summary    : GUPnP DLNA utility for DLNA-related tasks.
description: |
    GUPnP DLNA is a small utility library that aims to ease the DLNA-related tasks such as media profile guessing, transcoding to a given profile, etc.
builddeps  :
    - pkgconfig(libxml-2.0)
    - pkgconfig(glib-2.0)
    - pkgconfig(gobject-2.0)
    - pkgconfig(gmodule-2.0)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-pbutils-1.0)
    - vala
setup      : |
    # this package forces -O0 over our -O2 which breaks FORTIFY_SOURCE
    %configure --disable-static \
               CFLAGS="${CFLAGS/-D_FORTIFY_SOURCE=2/}"
build      : |
    %make
install    : |
    # this is just a really bad package now.
    %make_install -j1
